apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vm-console-proxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/aaguirre-tenant/vm-console-proxy/vm-console-proxy@sha256:8ddc772f98122b969fd823de4236eb77c2595d193b76d98eb94f460fddb3925d
        name: container-image
        resources: {}
status: {}
