apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vm-console-proxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/aaguirre-tenant/vm-console-proxy/vm-console-proxy@sha256:b6927a428097f6d62b259d3362dc8a3c4c10a4ed301207087bb976f92dc2952a
        name: container-image
        resources: {}
status: {}
