apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vm-console-proxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/aaguirre-tenant/vm-console-proxy/vm-console-proxy@sha256:61655ec703f34f8d7aef43ca555f3d21c840b5d2c15e97ffba0486a9b2638359
        name: container-image
        resources: {}
status: {}
