apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vm-console-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vm-console-proxy
    app.kubernetes.io/part-of: vm-console-proxy
  name: vm-console-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: vm-console-proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vm-console-proxy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/aaguirre-tenant/vm-console-proxy/vm-console-proxy@sha256:b6927a428097f6d62b259d3362dc8a3c4c10a4ed301207087bb976f92dc2952a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
