apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vm-console-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vm-console-proxy
    app.kubernetes.io/part-of: vm-console-proxy
  name: vm-console-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: vm-console-proxy
status:
  loadBalancer: {}
